export const data = [
    {
        id: 1,
        name: "Raj Patel",
        email: "raj.patel@company.com",
        role: "Admin",
        status: "Active",
        age: 32,
        country: "India",
    },
    {
        id: 2,
        name: "Emma Smith",
        email: "emma.smith@company.com",
        role: "Employee",
        status: "Inactive",
        age: 27,
        country: "USA",
    },
    {
        id: 3,
        name: "Liam Chen",
        email: "liam.chen@company.com",
        role: "Manager",
        status: "Active",
        age: 45,
        country: "China",
    },
    {
        id: 4,
        name: "Olivia Garcia",
        email: "olivia.garcia@company.com",
        role: "Intern",
        status: "Pending",
        age: 22,
        country: "Spain",
    },
    {
        id: 5,
        name: "Noah Singh",
        email: "noah.singh@company.com",
        role: "Employee",
        status: "Active",
        age: 29,
        country: "India",
    },
    {
        id: 6,
        name: "Ava Kumar",
        email: "ava.kumar@company.com",
        role: "Manager",
        status: "Inactive",
        age: 41,
        country: "UK",
    },
    {
        id: 7,
        name: "Ethan Johnson",
        email: "ethan.johnson@company.com",
        role: "Employee",
        status: "Active",
        age: 35,
        country: "USA",
    },
    {
        id: 8,
        name: "Sophia Lopez",
        email: "sophia.lopez@company.com",
        role: "Intern",
        status: "Pending",
        age: 23,
        country: "Mexico",
    },
    {
        id: 9,
        name: "Mason Brown",
        email: "mason.brown@company.com",
        role: "Employee",
        status: "Active",
        age: 30,
        country: "Australia",
    },
    {
        id: 10,
        name: "Isabella Jones",
        email: "isabella.jones@company.com",
        role: "Admin",
        status: "Active",
        age: 38,
        country: "Canada",
    },
    {
        id: 11,
        name: "Lucas Wilson",
        email: "lucas.wilson@company.com",
        role: "Manager",
        status: "Inactive",
        age: 43,
        country: "USA",
    },
    {
        id: 12,
        name: "Mia Taylor",
        email: "mia.taylor@company.com",
        role: "Intern",
        status: "Pending",
        age: 21,
        country: "UK",
    },
    {
        id: 13,
        name: "James Martinez",
        email: "james.martinez@company.com",
        role: "Employee",
        status: "Active",
        age: 31,
        country: "Spain",
    },
    {
        id: 14,
        name: "Amelia Hernandez",
        email: "amelia.hernandez@company.com",
        role: "Manager",
        status: "Active",
        age: 39,
        country: "Mexico",
    },
    {
        id: 15,
        name: "Benjamin Lee",
        email: "benjamin.lee@company.com",
        role: "Employee",
        status: "Inactive",
        age: 36,
        country: "China",
    },
    {
        id: 16,
        name: "Charlotte Davis",
        email: "charlotte.davis@company.com",
        role: "Admin",
        status: "Active",
        age: 33,
        country: "USA",
    },
    {
        id: 17,
        name: "Elijah Miller",
        email: "elijah.miller@company.com",
        role: "Employee",
        status: "Pending",
        age: 25,
        country: "Australia",
    },
    {
        id: 18,
        name: "Harper Moore",
        email: "harper.moore@company.com",
        role: "Manager",
        status: "Active",
        age: 40,
        country: "UK",
    },
    {
        id: 19,
        name: "William Jackson",
        email: "william.jackson@company.com",
        role: "Intern",
        status: "Inactive",
        age: 24,
        country: "USA",
    },
    {
        id: 20,
        name: "Evelyn Thompson",
        email: "evelyn.thompson@company.com",
        role: "Admin",
        status: "Active",
        age: 37,
        country: "Canada",
    },
    {
        id: 21,
        name: "Henry White",
        email: "henry.white@company.com",
        role: "Employee",
        status: "Active",
        age: 29,
        country: "India",
    },
    {
        id: 22,
        name: "Scarlett Harris",
        email: "scarlett.harris@company.com",
        role: "Manager",
        status: "Pending",
        age: 34,
        country: "UK",
    },
    {
        id: 23,
        name: "Alexander Martin",
        email: "alexander.martin@company.com",
        role: "Employee",
        status: "Inactive",
        age: 42,
        country: "USA",
    },
    {
        id: 24,
        name: "Ella Thompson",
        email: "ella.thompson@company.com",
        role: "Intern",
        status: "Active",
        age: 22,
        country: "Canada",
    },
    {
        id: 25,
        name: "Michael Walker",
        email: "michael.walker@company.com",
        role: "Manager",
        status: "Active",
        age: 44,
        country: "Australia",
    },
    {
        id: 26,
        name: "Luna Young",
        email: "luna.young@company.com",
        role: "Employee",
        status: "Pending",
        age: 28,
        country: "UK",
    },
    {
        id: 27,
        name: "Daniel Allen",
        email: "daniel.allen@company.com",
        role: "Admin",
        status: "Inactive",
        age: 39,
        country: "USA",
    },
    {
        id: 28,
        name: "Avery King",
        email: "avery.king@company.com",
        role: "Employee",
        status: "Active",
        age: 31,
        country: "Spain",
    },
    {
        id: 29,
        name: "Matthew Wright",
        email: "matthew.wright@company.com",
        role: "Manager",
        status: "Active",
        age: 46,
        country: "Canada",
    },
    {
        id: 30,
        name: "Sofia Scott",
        email: "sofia.scott@company.com",
        role: "Intern",
        status: "Inactive",
        age: 23,
        country: "Australia",
    },
    {
        id: 31,
        name: "Jack Green",
        email: "jack.green@company.com",
        role: "Employee",
        status: "Active",
        age: 35,
        country: "USA",
    },
    {
        id: 32,
        name: "Chloe Adams",
        email: "chloe.adams@company.com",
        role: "Manager",
        status: "Pending",
        age: 30,
        country: "UK",
    },
    {
        id: 33,
        name: "Sebastian Baker",
        email: "sebastian.baker@company.com",
        role: "Employee",
        status: "Inactive",
        age: 38,
        country: "India",
    },
    {
        id: 34,
        name: "Grace Gonzalez",
        email: "grace.gonzalez@company.com",
        role: "Intern",
        status: "Active",
        age: 21,
        country: "Spain",
    },
    {
        id: 35,
        name: "Samuel Nelson",
        email: "samuel.nelson@company.com",
        role: "Employee",
        status: "Active",
        age: 33,
        country: "Australia",
    },
    {
        id: 36,
        name: "Victoria Carter",
        email: "victoria.carter@company.com",
        role: "Manager",
        status: "Inactive",
        age: 41,
        country: "Canada",
    },
    {
        id: 37,
        name: "Joseph Rivera",
        email: "joseph.rivera@company.com",
        role: "Admin",
        status: "Active",
        age: 43,
        country: "USA",
    },
    {
        id: 38,
        name: "Eleanor Perez",
        email: "eleanor.perez@company.com",
        role: "Employee",
        status: "Pending",
        age: 27,
        country: "Mexico",
    },
    {
        id: 39,
        name: "David Roberts",
        email: "david.roberts@company.com",
        role: "Employee",
        status: "Active",
        age: 29,
        country: "UK",
    },
    {
        id: 40,
        name: "Aria Turner",
        email: "aria.turner@company.com",
        role: "Manager",
        status: "Inactive",
        age: 40,
        country: "Spain",
    },
    {
        id: 41,
        name: "John Torres",
        email: "john.torres@company.com",
        role: "Employee",
        status: "Active",
        age: 32,
        country: "India",
    },
    {
        id: 42,
        name: "Layla Ramirez",
        email: "layla.ramirez@company.com",
        role: "Intern",
        status: "Pending",
        age: 24,
        country: "USA",
    },
    {
        id: 43,
        name: "Wyatt Kelly",
        email: "wyatt.kelly@company.com",
        role: "Employee",
        status: "Active",
        age: 36,
        country: "Australia",
    },
    {
        id: 44,
        name: "Nora Barnes",
        email: "nora.barnes@company.com",
        role: "Manager",
        status: "Inactive",
        age: 42,
        country: "Canada",
    },
    {
        id: 45,
        name: "Owen Ross",
        email: "owen.ross@company.com",
        role: "Employee",
        status: "Active",
        age: 34,
        country: "UK",
    },
    {
        id: 46,
        name: "Hannah Murphy",
        email: "hannah.murphy@company.com",
        role: "Intern",
        status: "Pending",
        age: 22,
        country: "Ireland",
    },
    {
        id: 47,
        name: "Gabriel Cook",
        email: "gabriel.cook@company.com",
        role: "Manager",
        status: "Active",
        age: 39,
        country: "USA",
    },
    {
        id: 48,
        name: "Zoe Bailey",
        email: "zoe.bailey@company.com",
        role: "Employee",
        status: "Inactive",
        age: 28,
        country: "Australia",
    },
    {
        id: 49,
        name: "Logan Cooper",
        email: "logan.cooper@company.com",
        role: "Employee",
        status: "Active",
        age: 31,
        country: "India",
    },
    {
        id: 50,
        name: "Lily Reed",
        email: "lily.reed@company.com",
        role: "Manager",
        status: "Pending",
        age: 26,
        country: "USA",
    },
];
